from typing import Protocol


class RateLimiter(Protocol):
    def allow_request(self, required_tokens: int = 1) -> bool: ...
    def get_remaining(self) -> int: ...
    def get_reset_time(self) -> float: ...
